#!/usr/bin/sh
#A wrapper script for the workaround a missing opera_autoupdate RPATH.
PATHORIG=${PATH}
PATH=/usr/lib64/opera-developer:/usr/lib64/opera-developer/lib:${PATH}
LD_LIBRARY_PATH=/usr/lib64/opera-developer/lib opera_autoupdate_orig
PATH=${PATHORIG}
exit 0
